In [3]:
import tensorflow as tf
#for generating numbers
import random

In [14]:
#Independent variable(x)
x = tf.constant([1,2,3,4,5,6], tf.float32)

#dependent variable(y)
y = tf.constant([100, 200, 300, 400, 500, 600], tf.float32)

In [16]:
# Weight (w)
w = tf.Variable(tf.constant(random.uniform(0,1)))

#bias
b = tf.Variable(tf.constant(random.uniform(0,1)))


In [17]:
print(x)

tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)


In [18]:
print(y)

tf.Tensor([100. 200. 300. 400. 500. 600.], shape=(6,), dtype=float32)


In [19]:
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.5277656>


In [20]:
print(b)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.3797537>


In [21]:
def predict(x, w, b):
    y_hat = tf.multiply(w,x) + b
    return y_hat

In [22]:
prediction = predict(x, w, b)
print(prediction)

tf.Tensor([0.9075193 1.4352849 1.9630505 2.490816  3.0185814 3.5463471], shape=(6,), dtype=float32)


In [23]:
def loss(y_hat, y):
    squared_error = tf.square(y_hat - y)
    msc = tf.reduce_mean(squared_error)
    return msc

In [24]:
print(loss(prediction, y))

tf.Tensor(149805.73, shape=(), dtype=float32)


In [30]:
# create a train function which will compute the loss and update the values of
#weight and bias using gradient descent

def train(x,y,w,b):
    #define the learing rate
    
    learing_rate = 0.05
    
    with tf.GradientTape() as t:
        #grt prediction
        y_hat = predict(x, w, b)
        
        #compute the loss
        step_loss = loss(y_hat, y)
    #find the gradient
    grad_w, grad_b = t.gradient(step_loss, [w,b])
    
    #update weight
    w.assign_sub(learing_rate * grad_w)
    
    #update bias b = b- learing_rate * grad_b
    b.assign_sub(learing_rate * grad_b)

In [31]:
#training for 2000 steps
#intialize the model

for epoch in range(2000):
    
    #train the model
    train(x, y, w, b)

In [32]:
#predict the predictions
prediction = predict(x, w, b)
print(prediction)

tf.Tensor([100.000015 200.00002  300.00003  400.00003  500.00003  600.      ], shape=(6,), dtype=float32)


In [37]:
print(loss(prediction, y))

tf.Tensor(5.432715e-10, shape=(), dtype=float32)
