In [1]:
import tensorflow as tf

In [2]:
t1 = tf.constant([10,11,12,13])
t2 = tf.constant([1,2,3,4])

In [3]:
#add() method
print(tf.add(t1,t2))

tf.Tensor([11 13 15 17], shape=(4,), dtype=int32)


In [4]:
print(t1+t2)

tf.Tensor([11 13 15 17], shape=(4,), dtype=int32)


In [5]:
print(tf.subtract(t1,t2))

tf.Tensor([9 9 9 9], shape=(4,), dtype=int32)


In [6]:
print(t1-t2)

tf.Tensor([9 9 9 9], shape=(4,), dtype=int32)


In [7]:
print(tf.multiply(t1,t2))

tf.Tensor([10 22 36 52], shape=(4,), dtype=int32)


In [8]:
print(t1*t2)

tf.Tensor([10 22 36 52], shape=(4,), dtype=int32)


In [9]:
t1 = tf.constant([2,4,6,8])
t2 = tf.constant([1,2,3,4])

In [10]:
print(tf.divide(t1,t2))

tf.Tensor([2. 2. 2. 2.], shape=(4,), dtype=float64)


In [12]:
print(tf.square(t1))
print(tf.square(t2))

tf.Tensor([ 4 16 36 64], shape=(4,), dtype=int32)
tf.Tensor([ 1  4  9 16], shape=(4,), dtype=int32)


In [13]:
# for mean value  reduce_method() is used
print(tf.reduce_mean(t1))
print(tf.reduce_mean(t2))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [15]:
#multiple operations
print(t1 + tf.reduce_mean(t1) - t1)

tf.Tensor([5 5 5 5], shape=(4,), dtype=int32)
