In [8]:
import tensorflow as tf

In [9]:
print(tf.constant(3))

tf.Tensor(3, shape=(), dtype=int32)


In [10]:
scaler = tf.constant(3)
print(scaler)

tf.Tensor(3, shape=(), dtype=int32)


In [13]:
scaler = tf.constant(3, tf.float64)
print(scaler)

tf.Tensor(3.0, shape=(), dtype=float64)


In [14]:
print(scaler.shape)

()


In [15]:
print(scaler.dtype)

<dtype: 'float64'>


In [16]:
print(scaler.numpy())

3.0


In [19]:
#A 1D Tensor  has a single dimension or axis and is a vector
rank_1_tensor = tf.constant([1, 2, 3], tf.float64)
print(rank_1_tensor)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


In [22]:
#A 2D tensor has two dimension or axes and is a matrix
rank_2_tensor = tf.constant([[1,2],
                            [4,5],
                            [8,9]])
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [4 5]
 [8 9]], shape=(3, 2), dtype=int32)


In [24]:
#A 3D tensor has three dimension or axes 
rank_3_tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[8,9,0]]])
print(rank_3_tensor)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [8 9 0]]], shape=(2, 2, 3), dtype=int32)
